import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Button } from '@nextui-org/react';


const Home: NextPage = () => {




  return (
  
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">FenixBois.js!</a>
          <Button>Krasné tlačítko</Button>
        </h1>

        
    </div>
  )
}

export default Home
